### ISSUE TITLE
QPong 1.0

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-hackathon-korea-21#19]
# Abstract

Feb 28 this year is the 2nd anniversary of [QPong](https://www.youtube.com/watch?v=a1NZC5rqQD8). Let's make QPong even more awesome (& to reach 1.0 finally!)! 

# Description 

These are the new features I have in mind:

- [ ] Local multiplayer
- [ ] Match IQX circuit composer style
- [ ] Use latest Qiskit version
- [ ] Clean up the code and make it modular
- [ ] Online multiplayer (challenging)

If we could manage to make an online multilayer version of QPong, we can host online QPong competitions!

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @HuangJunye  

# Deliverable

PRs to [QPong repo](https://github.com/HuangJunye/QPong) and a Qiskit Medium blogpost

# GitHub repo

https://github.com/HuangJunye/QPong

**Comment by x2ever** [comment]
Hi I am very interested in this project, can I participate too? In addition to the contributions presented above, I would also like to make a contribution to create an OpenAI gym environment for reinforcement learning with Qpong.

**Comment by HuangJunye** [comment]
@x2ever That's a great idea! I would love to see reinforcement learning of playing QPong :)

**Comment by HuangJunye** [comment]
Sorry, I won't be available for the next few hours until 6pm KST today.

Here are a few things you can do in the meanwhile:

- Download [QPong](https://github.com/HuangJunye/QPong) and play with it a little bit
- Brainstorm features that you would like to add in addition to those listed
- Choose features that are important and feasible to be implemented during hackathon

**Comment by x2ever** [comment]
Okay. I am happy to collaborate with you.

**Comment by HuangJunye** [comment]
@x2ever Seems you are the only one interested in the project. We may not find enough people to start the project...

**Comment by 0sophy1** [comment]
> Okay. I am happy to collaborate with you.

Hi, x2ever! Did you register 2022 hackathon? we will re-raise this issue. If you are interested in join again, please register! 
https://qiskithackkorea.creatorlink.net/
