### ISSUE TITLE
Compute qubit permutations in the StochasticSwap mapper

### ISSUE THREAD

**Issue by nonhermitian** [qiskit-community/qiskit-hackathon-korea-21#2]
# Abstract

Compute the permutation of qubits from their initial placements, e.g. `[0,1,2,3,4]`, to their permuted positions, e.g. `[1,2,0,4,3]` after being passed through the `StochasticSwap` mapper:

https://qiskit.org/documentation/stubs/qiskit.transpiler.passes.StochasticSwap.html#qiskit.transpiler.passes.StochasticSwap
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/routing/stochastic_swap.py
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx

# Description 
In order to execute a quantum circuit on a real system, the circuit must be first mapped to the device topology.  This generically requires introducing SWAP gates into the circuit that switch the states of two qubits.  For background see the supplementary info here:

https://qiskit.org/documentation/apidoc/transpiler.html

The permutation of qubits at the end of the circuit is important information to know when trying to understand where the virtual qubits in a circuit got mapped to on a real device.  Currently Qiskit does not track this permutation information, and one must get it by attaching measurements to the qubits with known classical bit ordering.  For example:

Initial circuit:

```python

qc = QuantumCircuit(5)
qc.x(4)
qc.h(range(5))
qc.cx([0,2,3],4)
qc.barrier()
qc.h(range(5))
qc.barrier()
qc.measure_all()
qc.draw()
```
```
        ┌───┐                     ░ ┌───┐ ░  ░ ┌─┐            
   q_0: ┤ H ├───────■─────────────░─┤ H ├─░──░─┤M├────────────
        ├───┤       │             ░ ├───┤ ░  ░ └╥┘┌─┐         
   q_1: ┤ H ├───────┼─────────────░─┤ H ├─░──░──╫─┤M├─────────
        ├───┤       │             ░ ├───┤ ░  ░  ║ └╥┘┌─┐      
   q_2: ┤ H ├───────┼────■────────░─┤ H ├─░──░──╫──╫─┤M├──────
        ├───┤       │    │        ░ ├───┤ ░  ░  ║  ║ └╥┘┌─┐   
   q_3: ┤ H ├───────┼────┼────■───░─┤ H ├─░──░──╫──╫──╫─┤M├───
        ├───┤┌───┐┌─┴─┐┌─┴─┐┌─┴─┐ ░ ├───┤ ░  ░  ║  ║  ║ └╥┘┌─┐
   q_4: ┤ X ├┤ H ├┤ X ├┤ X ├┤ X ├─░─┤ H ├─░──░──╫──╫──╫──╫─┤M├
        └───┘└───┘└───┘└───┘└───┘ ░ └───┘ ░  ░  ║  ║  ║  ║ └╥┘
meas: 5/════════════════════════════════════════╩══╩══╩══╩══╩═
                                                0  1  2  3  4 
```

can get mapped as follows:

```python

from qiskit.test.mock.backends import FakeAthens
backend = FakeAthens()
trans_qc = transpile(qc, backend)
trans_qc.draw()
```

```
         ┌─────────┐     ┌───┐                                             »
q_4 -> 0 ┤ U2(π,π) ├──■──┤ X ├──■──────────────────────────────────────────»
         ├─────────┤┌─┴─┐└─┬─┘┌─┴─┐               ┌───┐     ┌───┐          »
q_3 -> 1 ┤ U2(0,π) ├┤ X ├──■──┤ X ├───────────────┤ X ├──■──┤ X ├──■───────»
         ├─────────┤└───┘     └───┘     ┌───┐     └─┬─┘┌─┴─┐└─┬─┘┌─┴─┐┌───┐»
q_2 -> 2 ┤ U2(0,π) ├─────────────────■──┤ X ├──■────■──┤ X ├──■──┤ X ├┤ X ├»
         ├─────────┤     ┌───┐     ┌─┴─┐└─┬─┘┌─┴─┐     └───┘     └───┘└─┬─┘»
q_1 -> 3 ┤ U2(0,π) ├──■──┤ X ├──■──┤ X ├──■──┤ X ├──────────────────────■──»
         ├─────────┤┌─┴─┐└─┬─┘┌─┴─┐└───┘     └───┘                         »
q_0 -> 4 ┤ U2(0,π) ├┤ X ├──■──┤ X ├────────────────────────────────────────»
         └─────────┘└───┘     └───┘                                        »
 meas: 5/══════════════════════════════════════════════════════════════════»
                                                                           »
«                              ░ ┌─────────┐ ░          ┌─┐   
«q_4 -> 0 ─────────────────■───░─┤ U2(0,π) ├─░──────────┤M├───
«              ┌───┐     ┌─┴─┐ ░ ├─────────┤ ░          └╥┘┌─┐
«q_3 -> 1 ──■──┤ X ├──■──┤ X ├─░─┤ U2(0,π) ├─░───────────╫─┤M├
«         ┌─┴─┐└─┬─┘┌─┴─┐└───┘ ░ ├─────────┤ ░ ┌─┐       ║ └╥┘
«q_2 -> 2 ┤ X ├──■──┤ X ├──────░─┤ U2(0,π) ├─░─┤M├───────╫──╫─
«         └───┘     └───┘      ░ ├─────────┤ ░ └╥┘   ┌─┐ ║  ║ 
«q_1 -> 3 ─────────────────────░─┤ U2(0,π) ├─░──╫────┤M├─╫──╫─
«                              ░ ├─────────┤ ░  ║ ┌─┐└╥┘ ║  ║ 
«q_0 -> 4 ─────────────────────░─┤ U2(0,π) ├─░──╫─┤M├─╫──╫──╫─
«                              ░ └─────────┘ ░  ║ └╥┘ ║  ║  ║ 
« meas: 5/══════════════════════════════════════╩══╩══╩══╩══╩═
«                                               0  1  2  3  4 
```

where I can see by looking at the measurements and the classical bits that qubit 0 -> 2, qubit 1-> 4, qubit 2-> 3 etc.

The goal of this project is to compute this permutation information internally for the `StochasticSwap` routine, and attach it as metadata to the circuit output by the transpiler.  This is important for understanding the mapping of circuits,and computing the equivalence of unitary operators, where an un-mapped unitary circuit and the corresponding transpiled version are equal up to a one-sided permutation matrix. 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @nonhermitian 

# Deliverable
Code that computes the qubit permutation to be included in Qiskit.

# GitHub repo

**Comment by AnnaMHua** [comment]
Hi @nonhermitian have you finished this project? How can I access the final layout after transpile? Thank you!

**Comment by nonhermitian** [comment]
It has not been worked on yet. You are more than welcome to give it a go.

**Comment by AnnaMHua** [comment]
> It has not been worked on yet. You are more than welcome to give it a go.

Thanks for your reply. I will try it :)
