### ISSUE TITLE
Quantumafia

### ISSUE THREAD

**Issue by rhycha** [qiskit-community/qiskit-hackathon-korea-21#24]
# Abstract

It seems like the measurement is the judgment at Noon in mafia game.
We can consider '0' state as mafia, and '1' state as citizen.
So, Our goal is making the relation between mafia and citizen(maybe it is expressed as entanglement, I think.) using quantum circuit. First starting with 1 mafia and 1 citizen. and investigate what is the best choice along with each phase.
If possible, we can expend the people participated in mafia game, or add citizen who is doctor. 

# Description 

How do we do for our project?
I think making diverse circuit is the most important thing as an heuristic approach, 
While making circuit, we need to know what combination of components operate like mafia game.
To find where to put each circuit item, I think It's good to make truth table for each situations.
If possible, the knowledge of optimization problem is also important thing to make.
(Borrowing words by expers)

If the simulation operate well, we can expand this like 'Qpong'

Welcome everybody who join us,
Despite the difficulty, I will do my best. I don't give up.
So You don't have to worry that "Would We become wasting time doing nothing because of hardness in the middle of project?"
 

We need webinterface

# Members

 - @githubhandle 
 - 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by Rhycha** [comment]
And we need loving coach! we need help!
