### ISSUE TITLE
Variational Approach to Quantum State Discrimination

### ISSUE THREAD

**Issue by Mins0o** [qiskit-community/qiskit-hackathon-korea-21#28]
# Abstract  
Quantum state discrimination is an important task for quantum information processing. It is known that in quantum mechanics, one could only perfectly discriminate orthogonal states. When the states are non-orthogonal, several strategies can be adopted to discriminate them. One such strategy is the minimum error strategy where we minimize the probability of error resulting from imperfect discriminations. However, exact solution is only known for two states discrimination case.  
In this project, we are expecting a search based algorithm to help find the optimal quantum circuit for state discrimination.  
  
# Description  

  
# Members  
@taufiqmurtadho - Slack: `@Taufiq Murtadho`
@assemzh 
@ernchern - Slack: `@Ern Chern`
@john-mai-2605 - Slack: `@John Mai`
@mins0o - Slack: `@Minsoo Kang`
  
# Deliverable
Python code/Jupyter notebook
Visual representation of quantum circuit
PPT

# GitHub repo
[https://github.com/ernchern/qiskit-vaqsd](https://github.com/ernchern/qiskit-vaqsd)

**Comment by ernchern** [comment]
Thank you! Happy to join the team :)
