### ISSUE TITLE
Create a tutorial for Iterative Phase Estimation (IPE) algorithm

### ISSUE THREAD

**Issue by HwajungKang** [qiskit-community/qiskit-hackathon-korea-21#3]
# Abstract
The "length" of a quantum circuit is the primary factor when determining the magnitude of the errors in the resulting output distribution; quantum circuits with greater depth have decreased fidelity. Therefore, implementing algorithms based on shallow depth circuits is of the great importance in near-term quantum computing.  Iterative Phase Estimation (IPE) algorithm is one algorithm for estimating quantum phase called the Iterative Phase Estimation (IPE) algorithm which requires a system comprised of only a single ancillary qubit and evaluate the phase through a repeatative process.

# Description 
The Quantum Phase Estimation (QPE) circuit is limited by the number of qubits necessary for the algorithm’s precision. Every additional qubit has added costs in terms of noise and hardware requirements; noisy results that we obtained from executing the QPE circuit on a real quantum device would get worse as the number of the qubits on the circuit increases. The IPE algorithm implements quantum phase estimation with only a single ancillary qubit, and the accuracy of the algorithm is restricted by the number of iterations rather than the number of counting qubits. Therefore, IPE circuits are of practical interest and are of foremost importance for near-term quantum computing as QPE is an essential element in many quantum algorithms.

The goal of this project is for participants to understand the IPE algorithm by making its Qiskit tutorial.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @hwajungkang 

# Deliverable
Tutorial

# GitHub repo

**Comment by ikkoham** [comment]
Sounds interesting. I mention that the IQPE is just being refactored in the WIP pull request: https://github.com/Qiskit/qiskit-terra/pull/5642

**Comment by kjwcoo** [comment]
Can I join this project? I have been working on (classical) phase estimation in spin qubits and want to know about quantum phase estimation :)

**Comment by starktech23** [comment]
@kjwcoo Yes! Next step would be to find some teammates to make a team and select the idea. Feel free to use the Slack channel to reach out to people :)
