### ISSUE TITLE
Police Killings Occurrence Prediction

### ISSUE THREAD

**Issue by denniszhao97** [qiskit-community/qiskit-hackathon-korea-21#34]
# Abstract

# Description 

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by starktech23** [comment]
Hi @denniszhao97, you were probably looking to open this issue for the Northwestern Hackathon so I've closed it for this repo.
