### ISSUE TITLE
Create a Quantum Volume circuit generator for reproducible results.

### ISSUE THREAD

**Issue by nonhermitian** [qiskit-community/qiskit-hackathon-korea-21#6]
# Abstract
Quantum Volume (QV) is a holistic benchmark invented at IBM for gate-based quantum computing platforms.  This metric has gained traction amongst hardware makers as one of the key performance metrics for near-term quantum computers.  However, it is impossible to reproduce benchmark results from literature because there is no unique way to identify which QV circuits were executed.

This project aims to build a QV program that deterministically generates one or more QV circuits in a platform independent manner.  The QV circuits are generated using random numbers, so this would involve a generator that takes a `seed` value and `offset` (number of times the random generator has been called since seeding) and returns a circuit that is identical across all computing platforms.  Multiple circuits would be generated in sequence starting at a given seed and offset starting point.

# Description 
An initial idea (up for debate) is to label the circuits by the `seed` and `offset` values.  The circuits could be returned in a chosen gate basis, or left in the original SU(2) form.  The output would be Qiskit circuits or qasm files, with the option to output a collection of QV circuits in qasm form in a zip file.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @nonhermitian  

# Deliverable
A Python module called `quantum-volume` that implements the above idea.

# GitHub repo

**Comment by HuangJunye** [comment]
This project is very interesting. I am happy to be a co-coach for the Asia time when it's midnight for @nonhermitian.

**Comment by nonhermitian** [comment]
Thanks @HuangJunye!  It is indeed an interesting project (all my proposed projects are things that I want to do but sadly have no time to complete on my own).
